apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ns-pysleep
spec:
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer
  selector:
    app: redis


# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
#   namespace: ns-pysleep
# spec:
#   type: NodePort # Should only be used in development
#   ports:
#     - nodePort: 30379 # exposed node port
#       port: 6379 # service port
#       targetPort: 6379 # pod port
#   selector:
#     app: redis
