apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
  namespace: ns-pysleep
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: rahulh77/job-wq-2
        imagePullPolicy: Always
        env:
          - name: INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      restartPolicy: OnFailure
