apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  namespace: ns-pysleep
  labels:
    app: redis
spec:
  containers:
    - name: master
      image: redis
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
